# Generated by Django 5.2.8 on 2025-11-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="فقط برای مدیریت خودت", max_length=200
                    ),
                ),
                (
                    "media_file",
                    models.FileField(blank=True, null=True, upload_to="to_upload/"),
                ),
                (
                    "caption",
                    models.TextField(
                        blank=True,
                        help_text="می\u200cتونی خالی بذاری، Gemini برات می\u200cنویسه",
                    ),
                ),
                (
                    "auto_caption",
                    models.BooleanField(
                        default=True,
                        help_text="اگر تیک بخوره، Gemini کپشن می\u200cنویسه",
                    ),
                ),
                ("hashtags", models.CharField(blank=True, max_length=300)),
                (
                    "scheduled_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="اگر خالی باشه، فوری ارسال میشه",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("scheduled", "زمان\u200cبندی شده"),
                            ("sent", "ارسال شده"),
                            ("failed", "ناموفق"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
