# Generated by Django 5.0.6 on 2025-11-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploader", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="post",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="post",
            name="auto_caption",
            field=models.BooleanField(
                default=False, verbose_name="کپشن خودکار با هوش مصنوعی"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="caption",
            field=models.TextField(blank=True, verbose_name="کپشن دستی"),
        ),
        migrations.AlterField(
            model_name="post",
            name="error_message",
            field=models.TextField(
                blank=True, default="", verbose_name="خطا (اگر بود)"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="hashtags",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="هشتگ\u200cها"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="media_file",
            field=models.FileField(upload_to="to_upload/", verbose_name="فایل"),
        ),
        migrations.AlterField(
            model_name="post",
            name="scheduled_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="زمان\u200cبندی ارسال"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "پیش\u200cنویس"),
                    ("scheduled", "زمان\u200cبندی"),
                    ("sent", "ارسال شد"),
                    ("failed", "ناموفق"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="عنوان (اختیاری)"
            ),
        ),
    ]
