# Generated by Django 5.0.6 on 2025-11-30 19:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploader", "0002_remove_post_created_at_remove_post_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="ساخته شده در"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="auto_caption",
            field=models.BooleanField(
                default=False, verbose_name="کپشن خودکار با Gemini"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="error_message",
            field=models.TextField(blank=True, default="", verbose_name="خطا"),
        ),
        migrations.AlterField(
            model_name="post",
            name="hashtags",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="هشتگ\u200cها"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="scheduled_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="زمان\u200cبندی"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="ارسال شده در"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(blank=True, max_length=200, verbose_name="عنوان"),
        ),
    ]
