# Generated by Django 5.0.6 on 2025-12-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploader", "0003_post_created_at_alter_post_auto_caption_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="شماره محصول"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام محصول")),
                ("brand", models.CharField(max_length=100, verbose_name="برند")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="توضیحات کوتاه"),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="قیمت اصلی"
                    ),
                ),
                (
                    "discount_percent",
                    models.PositiveIntegerField(default=0, verbose_name="درصد تخفیف"),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        decimal_places=0,
                        editable=False,
                        max_digits=12,
                        verbose_name="قیمت نهایی",
                    ),
                ),
                (
                    "in_stock",
                    models.BooleanField(default=True, verbose_name="موجودی دارد؟"),
                ),
                (
                    "delivery_days",
                    models.CharField(
                        default="۳ تا ۵ روز کاری",
                        max_length=50,
                        verbose_name="زمان ارسال",
                    ),
                ),
                (
                    "media_file",
                    models.FileField(upload_to="products/", verbose_name="عکس محصول"),
                ),
                (
                    "hashtags",
                    models.CharField(
                        default="#محصول #فروشگاه #تخفیف",
                        max_length=500,
                        verbose_name="هشتگ\u200cها",
                    ),
                ),
                (
                    "admin_id",
                    models.CharField(
                        default="@aitelgram499",
                        max_length=50,
                        verbose_name="آیدی ادمین",
                    ),
                ),
                (
                    "scheduled_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان\u200cبندی ارسال"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("scheduled", "زمان\u200cبندی"),
                            ("sent", "ارسال شد"),
                            ("failed", "ناموفق"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
