# Generated by Django 5.0.6 on 2025-12-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploader", "0004_product_delete_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
        migrations.RemoveField(
            model_name="product",
            name="error_message",
        ),
        migrations.RemoveField(
            model_name="product",
            name="final_price",
        ),
        migrations.AddField(
            model_name="product",
            name="ai_caption",
            field=models.TextField(blank=True, verbose_name="کپشن هوش مصنوعی (خودکار)"),
        ),
        migrations.AddField(
            model_name="product",
            name="use_ai_caption",
            field=models.BooleanField(
                default=True, verbose_name="کپشن را هوش مصنوعی بنویسد؟"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, max_length=100, verbose_name="برند"),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount_percent",
            field=models.PositiveIntegerField(
                default=0, verbose_name="درصد تخفیف (۰ = بدون تخفیف)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="hashtags",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="هشتگ\u200cها (اختیاری)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="original_price",
            field=models.PositiveIntegerField(verbose_name="قیمت اصلی (تومان)"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_code",
            field=models.CharField(
                max_length=30, unique=True, verbose_name="شماره محصول"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "پیش\u200cنویس"),
                    ("scheduled", "زمان\u200cبندی شده"),
                    ("sent", "ارسال شد"),
                    ("failed", "ناموفق"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
    ]
