# Generated by Django 5.0.6 on 2025-12-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploader", "0005_remove_product_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="عنوان (اختیاری)"
                    ),
                ),
                (
                    "media_file",
                    models.FileField(
                        upload_to="posts/", verbose_name="فایل (عکس/ویدیو/سند)"
                    ),
                ),
                ("caption", models.TextField(blank=True, verbose_name="کپشن دستی")),
                (
                    "use_ai_caption",
                    models.BooleanField(
                        default=True, verbose_name="کپشن را هوش مصنوعی بنویسد؟"
                    ),
                ),
                (
                    "hashtags",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="هشتگ\u200cها"
                    ),
                ),
                (
                    "scheduled_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان\u200cبندی"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("scheduled", "زمان\u200cبندی"),
                            ("sent", "ارسال شد"),
                            ("failed", "ناموفق"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "پست معمولی",
                "verbose_name_plural": "پست\u200cهای معمولی",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "verbose_name": "محصول فروشگاه",
                "verbose_name_plural": "محصولات فروشگاه",
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="ai_caption",
        ),
        migrations.AlterField(
            model_name="product",
            name="discount_percent",
            field=models.PositiveIntegerField(default=0, verbose_name="درصد تخفیف"),
        ),
        migrations.AlterField(
            model_name="product",
            name="hashtags",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="هشتگ\u200cها"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="scheduled_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="زمان\u200cبندی"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "پیش\u200cنویس"),
                    ("scheduled", "زمان\u200cبندی"),
                    ("sent", "ارسال شد"),
                    ("failed", "ناموفق"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
    ]
