# Generated by Django 5.0.6 on 2025-12-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "uploader",
            "0006_post_alter_product_options_remove_product_ai_caption_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
        migrations.AddField(
            model_name="product",
            name="ai_caption",
            field=models.TextField(blank=True, verbose_name="کپشن هوش مصنوعی (خودکار)"),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="ساخته شده در"),
        ),
        migrations.AlterField(
            model_name="post",
            name="sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="ارسال شده در"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="use_ai_caption",
            field=models.BooleanField(
                default=False, verbose_name="کپشن را هوش مصنوعی بنویسد؟"
            ),
        ),
    ]
